# Generated by Django 2.1.7 on 2019-07-16 13:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uye_name', models.CharField(max_length=150, verbose_name='Üye Adı')),
                ('uye_bio', ckeditor.fields.RichTextField()),
                ('uye_slug', models.SlugField(unique=True)),
                ('uye_resim', models.ImageField(null=True, upload_to='', verbose_name='Üye Resmi 300x300px')),
            ],
        ),
    ]
