# Generated by Django 2.1.7 on 2019-07-16 14:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uye',
            options={'verbose_name': 'Üye', 'verbose_name_plural': 'Üyeler'},
        ),
        migrations.AddField(
            model_name='uye',
            name='uye_kidem',
            field=models.CharField(default='Null', max_length=150, verbose_name='Üye Kıdemi'),
        ),
        migrations.AlterField(
            model_name='uye',
            name='uye_bio',
            field=ckeditor.fields.RichTextField(verbose_name='Üye Biografisi'),
        ),
    ]
