# Generated by Django 2.1.7 on 2019-07-16 18:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190716_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaskanMesaji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baskan_mesaji', ckeditor.fields.RichTextField(verbose_name='Başkanın Mesajı')),
            ],
            options={
                'verbose_name': 'Başkanın Mesajı',
                'verbose_name_plural': 'Başkanın Mesajı',
            },
        ),
        migrations.AlterField(
            model_name='uye',
            name='uye_kidem',
            field=models.CharField(max_length=150, verbose_name='Üye Kıdemi'),
        ),
    ]
