# Generated by Django 2.1.7 on 2019-07-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190716_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='UyelikBasvurusu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basvuru_name', models.CharField(max_length=150, verbose_name='Başvurucu İsmi')),
                ('basvuru_dogumyeri_tarihi', models.CharField(max_length=150, verbose_name='Başvurucu Doğum Yeri ve Tarihi')),
                ('basvuru_tcno', models.CharField(max_length=150, verbose_name='Başvurucu TC Numarası')),
                ('basvuru_kurum', models.CharField(max_length=150, verbose_name='Başvurucu Çalıştığı Kurum')),
                ('basvuru_uzmanlik', models.CharField(max_length=150, verbose_name='Başvurucu Uzmanlık Alanı')),
                ('basvuru_meslekiunvan', models.CharField(max_length=150, verbose_name='Başvurucu Mesleki Ünvanı')),
                ('basvuru_telefon', models.CharField(max_length=150, verbose_name='Başvurucu Telefon Numarası')),
                ('basvuru_tarihi', models.DateField(auto_now_add=True, verbose_name='Başvurunun Yapıldığı Tarih')),
            ],
            options={
                'verbose_name': 'Üyelik Başvurusu',
                'verbose_name_plural': 'Üyelik Başvuruları',
            },
        ),
    ]
