# Generated by Django 2.1.7 on 2019-07-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_uyelikbasvurusu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iletisim_name', models.CharField(max_length=150, verbose_name='Ad-Soyad')),
                ('iletisim_contactinfo', models.CharField(max_length=150, verbose_name='İletişim Adresi')),
                ('iletisim_mesaj', models.TextField(verbose_name='İletişim Mesajı')),
                ('iletisim_tarihi', models.DateField(auto_now_add=True, verbose_name='İletişim Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim Talebi',
                'verbose_name_plural': 'İletişim Talepleri',
                'ordering': ('iletisim_tarihi',),
            },
        ),
        migrations.AlterModelOptions(
            name='uyelikbasvurusu',
            options={'ordering': ('-basvuru_tarihi',), 'verbose_name': 'Üyelik Başvurusu', 'verbose_name_plural': 'Üyelik Başvuruları'},
        ),
    ]
