# Generated by Django 2.2.3 on 2019-08-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190717_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='uye',
            name='uye_yk_durum',
            field=models.BooleanField(default=False, verbose_name='Yönetim Kurulu Üyesi'),
        ),
    ]
