# Generated by Django 2.2.3 on 2019-08-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_uye_uye_yk_durum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uye',
            options={'ordering': ('uye_order',), 'verbose_name': 'Üye', 'verbose_name_plural': 'Üyeler'},
        ),
        migrations.AddField(
            model_name='uye',
            name='uye_order',
            field=models.IntegerField(default=1, verbose_name='Üye Gösterim Sıralaması'),
        ),
    ]
