# Generated by Django 2.2.3 on 2019-08-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_kurul'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kurul',
            options={'verbose_name': 'Kurul', 'verbose_name_plural': 'Kurullar'},
        ),
        migrations.AddField(
            model_name='kurul',
            name='kurul_name_capital',
            field=models.CharField(default='kurul-default', max_length=150, verbose_name='Kurul Adı (Büyük Harf)'),
        ),
        migrations.AddField(
            model_name='kurul',
            name='kurul_slug',
            field=models.SlugField(default='kurul-default', unique=True),
        ),
    ]
