# Generated by Django 2.2.3 on 2019-08-25 18:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190825_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egitim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egitim_name', models.CharField(max_length=150, verbose_name='Eğitim Adı')),
                ('egitim_icerik', ckeditor.fields.RichTextField(verbose_name='Eğitim İçeriği')),
                ('egitim_tarihi', models.DateField(verbose_name='Eğitim Tarihi')),
                ('egitim_slug', models.SlugField(verbose_name='Eğitim Slug Adı')),
            ],
            options={
                'verbose_name': 'Eğitim',
                'verbose_name_plural': 'Eğitimler',
                'ordering': ('egitim_tarihi',),
            },
        ),
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etkinlik_name', models.CharField(max_length=150, verbose_name='Etkinlik Adı')),
                ('etkinlik_tarihi', models.DateField(verbose_name='Eğitim Tarihi')),
                ('etkinlik_icerik', ckeditor.fields.RichTextField(verbose_name='Etkinlik İçeriği')),
                ('etkinlik_slug', models.SlugField(verbose_name='Etkinlik Slug Adı')),
            ],
            options={
                'verbose_name': 'Etkinlik',
                'verbose_name_plural': 'Etkinlikler',
                'ordering': ('etkinlik_tarihi',),
            },
        ),
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_name', models.CharField(max_length=150, verbose_name='Proje Adı')),
                ('proje_tarihi', models.DateField(verbose_name='Proje Tarihi')),
                ('proje_icerik', ckeditor.fields.RichTextField(verbose_name='Proje İçeriği')),
                ('proje_slug', models.SlugField(verbose_name='Proje Slug Adı')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ('proje_tarihi',),
            },
        ),
        migrations.AlterField(
            model_name='kurul',
            name='kurul_icerik',
            field=ckeditor.fields.RichTextField(verbose_name='Kurul İçeriği'),
        ),
    ]
