# Generated by Django 2.2.3 on 2019-08-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20190825_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egitim',
            name='egitim_slug',
            field=models.SlugField(unique=True, verbose_name='Eğitim Slug Adı'),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='etkinlik_slug',
            field=models.SlugField(unique=True, verbose_name='Etkinlik Slug Adı'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='proje_slug',
            field=models.SlugField(unique=True, verbose_name='Proje Slug Adı'),
        ),
    ]
