# Generated by Django 2.2.3 on 2019-08-26 13:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20190825_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duyuru_name', models.CharField(max_length=150, verbose_name='Duyuru Başlığı')),
                ('duyuru_tarihi', models.DateField(verbose_name='Duyuru Tarihi')),
                ('duyuru_icerik', ckeditor.fields.RichTextField(verbose_name='Duyuru İçeriği')),
                ('duyuru_slug', models.SlugField(unique=True, verbose_name='Duyuru Slug')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ('-duyuru_tarihi',),
            },
        ),
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haber_name', models.CharField(max_length=150, verbose_name='Haber Başlığı')),
                ('haber_tarihi', models.DateField(verbose_name='Haber Tarihi')),
                ('haber_icerik', ckeditor.fields.RichTextField(verbose_name='Haber İçeriği')),
                ('haber_slug', models.SlugField(unique=True, verbose_name='Haber Slug')),
            ],
            options={
                'verbose_name': 'Haber',
                'verbose_name_plural': 'Haberler',
                'ordering': ('-haber_tarihi',),
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-iletisim_tarihi',), 'verbose_name': 'İletişim Talebi', 'verbose_name_plural': 'İletişim Talepleri'},
        ),
        migrations.AlterModelOptions(
            name='egitim',
            options={'ordering': ('-egitim_tarihi',), 'verbose_name': 'Eğitim', 'verbose_name_plural': 'Eğitimler'},
        ),
        migrations.AlterModelOptions(
            name='etkinlik',
            options={'ordering': ('-etkinlik_tarihi',), 'verbose_name': 'Yayın', 'verbose_name_plural': 'Yayınlar'},
        ),
        migrations.AlterModelOptions(
            name='proje',
            options={'ordering': ('-proje_tarihi',), 'verbose_name': 'Proje', 'verbose_name_plural': 'Projeler'},
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='etkinlik_icerik',
            field=ckeditor.fields.RichTextField(verbose_name='Yayın İçeriği'),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='etkinlik_name',
            field=models.CharField(max_length=150, verbose_name='Yayın Adı'),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='etkinlik_slug',
            field=models.SlugField(unique=True, verbose_name='Yayın Slug Adı'),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='etkinlik_tarihi',
            field=models.DateField(verbose_name='Yayın Tarihi'),
        ),
    ]
